// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/TykTechnologies/storage/temporal/model"
	mock "github.com/stretchr/testify/mock"
)

// DeleteAtomicOpt is an autogenerated mock type for the DeleteAtomicOpt type
type DeleteAtomicOpt struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DeleteAtomicOpt) Execute(_a0 *model.DeleteAtomicOption) {
	_m.Called(_a0)
}

// NewDeleteAtomicOpt creates a new instance of DeleteAtomicOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteAtomicOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteAtomicOpt {
	mock := &DeleteAtomicOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
