// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Set is an autogenerated mock type for the Set type
type Set struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, key, member
func (_m *Set) AddMember(ctx context.Context, key string, member string) error {
	ret := _m.Called(ctx, key, member)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsMember provides a mock function with given fields: ctx, key, member
func (_m *Set) IsMember(ctx context.Context, key string, member string) (bool, error) {
	ret := _m.Called(ctx, key, member)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, key, member)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, key, member)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Members provides a mock function with given fields: ctx, key
func (_m *Set) Members(ctx context.Context, key string) ([]string, error) {
	ret := _m.Called(ctx, key)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: ctx, key, member
func (_m *Set) RemoveMember(ctx context.Context, key string, member string) error {
	ret := _m.Called(ctx, key, member)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSet interface {
	mock.TestingT
	Cleanup(func())
}

// NewSet creates a new instance of Set. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSet(t mockConstructorTestingTNewSet) *Set {
	mock := &Set{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
