name: CI tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  GO_VERSION: "1.18"
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }} # base_ref for PRs is 'master', but merges read in ref_name


jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: "Checkout PR"
        uses: TykTechnologies/github-actions/.github/actions/checkout-pr@main
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}

      - name: "Get base ref"
        run: |
          git fetch origin ${{ env.BRANCH_NAME }}
          git rev-parse origin/${{ env.BRANCH_NAME }}

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/golangci-lint
          key: 'golangci-lint-${{ runner.os }}-${{ hashFiles(''**/go.sum'') }}'
          restore-keys: |
            golangci-lint-${{ runner.os }}-

      - name: Setup CI Tooling
        uses: shrink/actions-docker-extract@v3
        with:
          image: tykio/ci-tools:latest
          path: /usr/local/bin/golangci-lint
          destination: /usr/local/bin

      - run: golangci-lint version && golangci-lint cache status

      - name: golangci-lint
        if: ${{ github.event_name == 'pull_request' }}
        # This is a pull request, but exiting here skips CI tests (`needs: golangci-lint`). Exit code 0 to always run tests.
        # PR uses the "prod" config and must pass.
        run: |
          golangci-lint run --out-format colored-line-number,checkstyle:golangci-lint-report.json \
                            --issues-exit-code=0 --new-from-rev=origin/${{ env.BRANCH_NAME }} -v ./...

      - name: golangci-lint-on-push
        if: ${{ github.event_name == 'push' }}
        # Using the default config, reports stats to sonarcloud. No requirements on passing other than KPIs tracked in dev.
        run: |
          golangci-lint run --out-format checkstyle:golangci-lint-report.json --issues-exit-code=0 -v ./...

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: golangcilint
          retention-days: 1
          path: |
            golangci-lint-report.json

  test:
    name: Tests ${{ matrix.storagetype }} storage - DB ${{ matrix.database }} ${{ matrix.version }} ${{ matrix.instancetype }}
    needs: [golangci-lint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - storagetype: persistent
            database: mongo
            version: 4.4
          - storagetype: persistent
            database: mongo
            version: 4.2
          - storagetype: persistent
            database: mongo
            version: 7.0
          - storagetype: persistent
            database: mongo
            version: 6.0
          - storagetype: temporal
            database: redis
            version: 6.0.0
            instancetype: single
          - storagetype: temporal
            database: redis
            version: 7.0.0
            instancetype: single
          - storagetype: temporal
            database: redis
            version: 6.0.0
            instancetype: cluster
          - storagetype: temporal
            database: redis
            version: 7.0.0
            instancetype: cluster
          - storagetype: temporal
            database: redis
            version: 7.2.0
            instancetype: single
          - storagetype: temporal
            database: redis
            version: 7.0.0
            instancetype: TLS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3

      - if: ${{ matrix.database == 'mongo' }}
        name: Start MongoDB '${{ matrix.version }}'
        run: task -t bin/Taskfile-db.yml start-mongo MONGO_VERSION=${{ matrix.version }}

      - if: ${{ matrix.database == 'redis' }}
        name: Start Redis '${{ matrix.version }}'
        run: task -t bin/Taskfile-db.yml start-redis-${{matrix.instancetype}} REDIS_VERSION=${{ matrix.version }}

      - name: Run tests
        env:
          DB: ${{ matrix.database }}
          DB_SETUP: ${{ matrix.instancetype }}
          DB_VERSION: ${{ matrix.version }}
        run: task test-${{ matrix.storagetype }}

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          retention-days: 1
          path: coverage/**/*.cov

  sonar-cloud-analysis:
    runs-on: ubuntu-latest
    needs: [test, golangci-lint]
    steps:
      - name: Checkout Tyk Storage
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Download coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - name: Download golangcilint artifacts
        uses: actions/download-artifact@v3
        with:
          name: golangcilint
      - name: Check reports existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "coverage/*.cov, golanglint.xml"
      - name: Install Dependencies
        env:
          TOKEN: "${{ secrets.ORG_GH_TOKEN }}"
        run: >
          git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"

          go install github.com/wadey/gocovmerge@latest
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3
      - name: merge reports
        run: task merge-coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=tyktechnologies
            -Dsonar.projectKey=TykTechnologies_storage
            -Dsonar.sources=.
            -Dsonar.coverage.exclusions=**/*_test.go,**/mocks/*.go,**/tempmocks/*.go
            -Dsonar.exclusions=**/mocks/*.go,**/tempmocks/*.go
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.tests=.
            -Dsonar.go.coverage.reportPaths=merged-coverage.cov
            -Dsonar.go.golangci-lint.reportPaths=golanglint.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
