name: Temporal Storage Tests

on:
  pull_request:
    branches:
      - main

env:
  REDIS_HOST: localhost
  GO_VERSION: "1.19.x"

jobs:
  test:
    name: DB ${{ matrix.database }} ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - database: redis
            version: 6
          - database: redis
            version: 7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - if: ${{ matrix.database == 'redis' }}
        name: Start Redis '${{ matrix.version }}'
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: "${{ matrix.version }}"

      - name: Run Redis tests
        run: |
          ./bin/temporal-storage-tests.sh ${{ matrix.database }} ${{ matrix.version }}

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          retention-days: 1
          path: |
            *.cov
