name: Visor

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  visor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add this step to set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Or the version specified in go.mod

      # Add this step to download Go module dependencies
      - name: Download Go dependencies
        run: go mod download
        
      - uses: probelabs/visor@main
        with:
          app-id: ${{ secrets.PROBE_APP_ID }}
          private-key: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.PROBE_APP_INSTALLATION_ID }}
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
