version: "3"

tasks:
  build:
    desc: "Build the project"
    cmds:
      - go build -v ./...

  run-tests:
    desc: "Run Go tests for temporal storage"
    cmds:
      - go test -p 1 -v -coverprofile=temporal.cov -cover -coverpkg=./... ./...