version: "3"

tasks:
  build:
    desc: "Build the project"
    cmds:
      - go build -v ./...

run-tests:
  desc: "Run Go tests for temporal storage"
  cmds:
    - |
      if [ "{{.REDIS_SETUP}}" = "cluster" ]; then
        TEST_REDIS_ADDRS=localhost:7000 REDIS_ENABLE_CLUSTER=true go test -p 1 -v -coverprofile=temporal.cov -cover -coverpkg=./... ./...
      else
        go test -p 1 -v -coverprofile=temporal.cov -cover -coverpkg=./... ./...
      fi

      test_exit_status=$?

      unset TEST_REDIS_ADDRS REDIS_ENABLE_CLUSTER

      exit $test_exit_status

  generate-mocks:
    desc: "Generate mocks for testing"
    deps:
      - install-mockery
    cmds:
      - mockery --all --keeptree --case=underscore --dir=model --output=tempmocks
    sources:
      - "./model/*.go"

  install-mockery:
    desc: "Install mockery v2"
    status:
      - type mockery
    cmds:
      - go install github.com/vektra/mockery/v2@v2.38.0
